package org.pacos.base.component.icon;

import java.util.Locale;

import com.vaadin.flow.component.dependency.JsModule;
import com.vaadin.flow.component.icon.IconFactory;

/**
 * Sets of SVG mime icon loaded from my-icons-mime.js
 * Autogenerated by Vaadin Icon
 */
@JsModule("./icons/my-icons-mime.js")
public enum MimeIcon implements IconFactory {
    BLACK, BLANK, CSV, FOLDER, HTML, JPG, KEY, LOG, TXT, VIDEO, XML, ZIP, GREEN, BPMN;

    public Icon create() {
        return new Icon(this.name().toLowerCase(Locale.ENGLISH).replace('_', '-').replaceAll("^-", ""));
    }

    public static final class Icon extends com.vaadin.flow.component.icon.Icon {

        Icon(String icon) {
            super("my-icons-mime", icon);
        }
    }
}