create table IF NOT EXISTS PUBLIC.APP_MODULE
(
    ID VARCHAR(36) PRIMARY KEY not null,
    REMOVED BOOLEAN default false,
    GROUP_ID VARCHAR(255) not null,
    ARTIFACT_NAME VARCHAR(255) not null,
    VERSION VARCHAR(50) not null,
    REPO_URL VARCHAR(1000)
);

create table IF NOT EXISTS PUBLIC.APP_PLUGIN
(
    ID VARCHAR(36) PRIMARY KEY not null,
    REMOVED BOOLEAN default false,
    DISABLED BOOLEAN default false,
    GROUP_ID VARCHAR(255) not null,
    ARTIFACT_NAME VARCHAR(255) not null,
    VERSION VARCHAR(50) not null,
    NAME VARCHAR(252) not null,
    AUTHOR VARCHAR(252),
    ICON VARCHAR(500),
    REPO_URL VARCHAR(1000)
);

INSERT INTO APP_MODULE SELECT * FROM APP_COUPLER_MODULE;
INSERT INTO APP_PLUGIN SELECT * FROM APP_COUPLER_PLUGIN;

DROP TABLE APP_COUPLER_MODULE;
DROP TABLE APP_COUPLER_PLUGIN;

