
INSERT INTO APP_PLUGIN(ID,REMOVED,DISABLED,GROUP_ID,ARTIFACT_NAME,VERSION,NAME)
VALUES('1',FALSE,FALSE,'org.pacos.plugin','explorer','1.0','explorer');
INSERT INTO APP_DEPENDENCY(ID,REMOVED,GROUP_ID,ARTIFACT_NAME,VERSION)
VALUES('2',FALSE,'org.gson','dependency','1.0');
INSERT INTO APP_DEPENDENCY(ID,REMOVED,GROUP_ID,ARTIFACT_NAME,VERSION)
VALUES('3',TRUE,'org.gson','removed','1.0');

INSERT INTO APP_PLUGIN(ID,REMOVED,DISABLED,GROUP_ID,ARTIFACT_NAME,VERSION,NAME)
VALUES('4',FALSE,TRUE,'org.pacos.plugin','database','1.0','database');

INSERT INTO APP_PLUGIN(ID,REMOVED,DISABLED,GROUP_ID,ARTIFACT_NAME,VERSION,NAME)
VALUES('5',TRUE,FALSE,'org.pacos.plugin','glogg','1.0','glogg');
INSERT INTO APP_PLUGIN_DEPENDENCY(PLUGIN_ID,DEPENDENCY_ID) VALUES('1','2');
INSERT INTO APP_PLUGIN_DEPENDENCY(PLUGIN_ID,DEPENDENCY_ID) VALUES('1','3');