create table IF NOT EXISTS APP_PLUGIN
(
    ID VARCHAR(36) PRIMARY KEY not null,
    REMOVED BOOLEAN default false,
    DISABLED BOOLEAN default false,
    GROUP_ID VARCHAR(255) not null,
    ARTIFACT_NAME VARCHAR(255) not null,
    VERSION VARCHAR(50) not null,
    NAME VARCHAR(252) not null,
    AUTHOR VARCHAR(252),
    ICON VARCHAR(500),
    REPO_URL VARCHAR(1000)
);

create table IF NOT EXISTS APP_DEPENDENCY
(
    ID VARCHAR(36) PRIMARY KEY not null,
    REMOVED BOOLEAN default false,
    GROUP_ID VARCHAR(255) not null,
    ARTIFACT_NAME VARCHAR(255) not null,
    VERSION VARCHAR(50) not null
);

create table IF NOT EXISTS APP_PLUGIN_DEPENDENCY
(
    PLUGIN_ID VARCHAR(36) not null,
    DEPENDENCY_ID VARCHAR(36) not null,
    PRIMARY KEY (PLUGIN_ID, DEPENDENCY_ID),
    FOREIGN KEY (PLUGIN_ID) REFERENCES PUBLIC.APP_PLUGIN (id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (DEPENDENCY_ID) REFERENCES PUBLIC.APP_DEPENDENCY (id) ON DELETE CASCADE ON UPDATE CASCADE
);
